// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://woccuvirqewuucsmrhol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvY2N1dmlycWV3dXVjc21yaG9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNzEwMTEsImV4cCI6MjA1ODY0NzAxMX0.Vl0ZQEqOyjTVVLji9jM8SJUVGL0WCP0hGVKWQaZSBvI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);